// Nigeria listed first since it's the shop's primary market and default.
export const COUNTRIES = [
  "Nigeria",
  "United States",
  "United Kingdom",
  "Canada",
  "Ghana",
  "South Africa",
  "Kenya",
  "Germany",
  "France",
  "Ireland",
  "Netherlands",
  "Belgium",
  "Spain",
  "Italy",
  "Portugal",
  "Sweden",
  "Norway",
  "Denmark",
  "Switzerland",
  "Austria",
  "Poland",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "India",
  "China",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Australia",
  "New Zealand",
  "Brazil",
  "Mexico",
  "Egypt",
  "Morocco",
  "Ethiopia",
  "Cameroon",
  "Cote d'Ivoire",
  "Senegal",
  "Togo",
  "Benin",
  "Other",
].sort((a, b) => (a === "Nigeria" ? -1 : b === "Nigeria" ? 1 : a.localeCompare(b)));
